Sdp 14 refactor game state management
logpacket/Invaders-SDP pull request #23
Opened 2024-12-01 04:37 UTC by mjwoon

Add GameState class

2024-12-01 05:58 UTC, logpacket requested changes

2024-12-01 05:58 UTC, logpacket commented on src/engine/GameState.java
> +        this.barriers = ConcurrentHashMap.newKeySet();
We don't need to consider race condition. Just use `HashSet`

2024-12-01 05:58 UTC, logpacket commented on src/engine/GameState.java
> +        this.isGameOver = false;
Initialize with `GameLevelState` instance. do not use literal value

2024-12-01 05:58 UTC, logpacket commented on src/engine/GameState.java
> +    }
We don't need getter and setter for level.

2024-12-01 05:58 UTC, logpacket commented on src/engine/GameState.java
> +    }
I think instead of this method, `lostLife` is fit to our game.
```java
public void lostLife() {
    this.lives--;
}
```

2024-12-01 05:58 UTC, logpacket commented on src/engine/GameState.java
> +    public GameState() {
Where are `enemyShipFormation`?

2024-12-01 05:58 UTC, logpacket commented on src/engine/GameState.java
> +    }
We don't need to implement this.

2024-12-02 15:06 UTC, mjwoon commented on src/engine/GameState.java
> +    public Set<Bullet> getBullets() {
asdf

2024-12-05 08:20 UTC, logpacket approved these changes

2024-12-05 08:20 UTC, merged