SDP-16 feat : implement ping and error pop ups
logpacket/Invaders-SDP pull request #25
Opened 2024-12-02 20:07 UTC by jiwoninnuk

Implemented ping feature on the game screen for real-time connectivity check.

Error pop-up added to notify the user when unable to connect to the server.

2024-12-02 20:13 UTC, jiwoninnuk commented
<img width="607" alt="스크린샷 2024-12-03 오전 5 11 44" src="https://github.com/user-attachments/assets/f6c42318-3c1f-4cf3-8173-34cd13463f78">
<img width="712" alt="스크린샷 2024-12-03 오전 5 12 23" src="https://github.com/user-attachments/assets/8402a873-ded1-4db8-ac8c-ba981a36ebe2">
<img width="1312" alt="스크린샷 2024-12-03 오전 5 13 48" src="https://github.com/user-attachments/assets/dd04d3d4-af9b-4539-82be-baae2dd2b32b">

2024-12-03 07:39 UTC, logpacket requested changes

2024-12-03 07:39 UTC, logpacket commented on src/screen/GameScreen.java
> +	}
I think is unnecessary method definition.
Just use `this.ping = NetworkManager.getLatency();`

2024-12-03 07:39 UTC, logpacket commented on src/screen/GameScreen.java
> +			updatePing();
Just use `this.ping = NetworkManager.getLatency;`

2024-12-05 09:04 UTC, logpacket approved these changes

2024-12-05 09:04 UTC, merged